mdapipkg/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>FirstName_SPE__c</fullName>
        <description>Encrypted First Name For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>First Name (PE)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <inlineHelpText>Please select the gender of the member.
M- Male
F- Female</inlineHelpText>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>Prefer not to mention</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LastName_SPE__c</fullName>
        <description>Encrypted Last Name For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Last Name (PE)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_City_SPE__c</fullName>
        <description>Encrypted Mailing City (PE) For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Mailing City (PE)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Country_SPE__c</fullName>
        <description>Encrypted Mailing Country (PE) For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Mailing Country (PE)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_State_Province_SPE__c</fullName>
        <description>Encrypted Mailing State (PE) For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Mailing State/Province (PE)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Street_SPE__c</fullName>
        <description>Encrypted Mailing Street (PE) For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Mailing  Street (PE)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Zip_Postal_Code_SPE__c</fullName>
        <description>Encrypted Mailing Zip/Postal Code (PE) For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Mailing Zip/Postal Code (PE)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonBirthdate_SPE__c</fullName>
        <description>Encrypted Birthdate For Members</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Birthdate (PE)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PersonEmail_SPE__c</fullName>
        <description>Encrypted Email For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Email (PE)</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone_SPE__c</fullName>
        <description>Encrypted Phone For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Phone (PE)</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Unsubscribe__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Unsubscribed from all communications from sleepvantage and ResMed.</description>
        <inlineHelpText>Check if patient wants to unsubscribe from all communications from sleepvantage and ResMed.</inlineHelpText>
        <label>Unsubscribe</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

mdapipkg/objects/Base_URL__mdt.object
<CustomObject>
    <description>This is the base URL of the target site exposed to the internet. The format of this URL MUST BE in the form of https://&lt;instance&gt;.force.com/services/apexrest/&lt;restResourceURLMapping&gt;.

Example: http://dev4ed-resmed-anz.cs6.force.com/SubscriptionProcessor/&lt;parameter&gt;</description>
    <label>Base URL</label>
    <pluralLabel>Base URLs</pluralLabel>
    <fields>
        <fullName>Base_URL__c</fullName>
        <label>Base URL</label>
        <type>Url</type>
    </fields>
</CustomObject>

mdapipkg/objects/Subscription_Map__c.object
<CustomObject>
    <description>A mapping table designed to store a subscription GUID, subscription type (e.g., SV Product Registration, MA Study, etc.), request flag, and account lookup. A record will be created each time an email (e.g., news letter, thank you, welcome, etc.) gets generated by Salesforce.com. The GUID is a unique ID assigned for each subscription type - and is the subject of &quot;unsubscribe&quot; request from the end user. When unsubscribe request is received, it will set the opt-out flag for that specific subscription type.</description>
    <label>Subscription Map</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{000000}</displayFormat>
        <label>Subscription Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account to which this subscription is mapped against.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscription Maps</relationshipLabel>
        <relationshipName>Subscription_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>A custom generated GUID assigned to each subscription record.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>GUID</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of subscription, e.g., SV Product Registration, MA Study, etc.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unsubscribe_URL__c</fullName>
        <description>The URL to unsubscribe service.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Unsubscribe URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Unsubscribed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies whether this account has already unsubscribed for this specific subscription.</description>
        <label>Unsubscribed</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/classes/TEST_SubscriptionProcessor.cls
/**
 * Class        : TEST_SubscriptionProcessor
 * Desctipion   : Test class for the RESTful API Web Service class - SubscriptionProcessor.cls
 * Date Created : 04-Mar-2020
 * Author       : eduardo.delarosa@resmed.com.au
 * App          : Generic - Marketing
 */

@isTest
public without sharing class TEST_SubscriptionProcessor {

    @TestSetup
    static void makeData() {

        String CLASS_NAME = 'TEST_SubscriptionProcessor | ';
        String SUBSCRIPTION_TYPE = 'Register Your Product';
        String BASE_URL_NAME = 'Subscription Processor';
        String REST_URL = '/services/apexrest/SubscriptionProcessor/';
        String base_url = NULL;
        String guid = NULL;
        Id testAccountId = NULL;
    
            // Step 1: Retrieve record type for Account
        RecordType recType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Member' AND SobjectType = 'Account' LIMIT 1];

        // Step 2: Create a test Member account
        Account testAcct = new Account(
                FirstName_SPE__c = 'Eduardo',
                FirstName = 'Eduardo',
                LastName_SPE__c = 'Dela Rosa - Unsubscribe',
                LastName = 'Dela Rosa - Unsubscribe',
                Gender__c = 'M',
                Mailing_City_SPE__c = 'Bella Vista',
                Mailing_Country_SPE__c = 'Australia',
                Mailing_State_Province_SPE__c = 'New South Wales',
                Mailing_Street_SPE__c = '1 Elizabeth Macarthur Drive',
                Mailing_Zip_Postal_Code_SPE__c = '2761',
                PersonBirthdate_SPE__c = Date.newInstance(2000,01,01),
                PersonEmail = 'eduardo.delarosa@resmed.com.au',
                PersonEmail_SPE__c = 'eduardo.delarosa@resmed.com.au',
                Phone_SPE__c = '0288842767',
                RecordTypeId = recType.Id,
                Salutation = 'Mr'
        );

        insert testAcct;
        testAccountId = testAcct.Id;

        // Step 3: Create a GUID
        GUIDGenerator gg = new GUIDGenerator(NULL);
        guid = gg.generateGUID(testAccountId);

        System.debug(CLASS_NAME + 'Id of the created test Account: ' + testAccountId);
        System.debug(CLASS_NAME + 'Value of the generated GUID: ' + guid);

        // Step 4: Retrieve the Base URL for unsubscribe type 'Register Your Product'
        base_url = [SELECT Id, Base_URL__c FROM Base_URL__mdt WHERE MasterLabel = 'Subscription Processor' LIMIT 1].Base_URL__c;
        System.debug(CLASS_NAME + 'Value of BASE_URL from Custom Metadata Setting: ' + BASE_URL);
        
        // Step 5: Insert a new entry into the Subscription Map sObject
        Subscription_Map__c subsMap = new Subscription_Map__c (
            Account__c = testAcct.Id,
            GUID__c = guid,
            Type__c = SUBSCRIPTION_TYPE,
            Unsubscribe_URL__c = base_url+REST_URL+guid,
            Unsubscribed__c = false
        );

        insert subsMap;

        System.debug(CLASS_NAME + 'Id of the created Subscription Map: ' + subsMap.Id);
        System.debug(CLASS_NAME + 'Value of the newly created Subscription Map: ' + subsMap);        
    }

    @isTest
    static void testDoGet () {

        // CONTINUE WORKING ON TEST
        // FOUND OUT THAT REGISTRATION IS NOT WORKING, TOO
        final String BASE_URL_NAME = 'Subscription Processor';
        final String REST_URL = '/services/apexrest/SubscriptionProcessor/';

        String base_url = [SELECT Id, Base_URL__c FROM Base_URL__mdt WHERE MasterLabel = 'Subscription Processor' LIMIT 1].Base_URL__c;

        // Before unsubscribe
        Subscription_Map__c subsMap = [SELECT Id, GUID__c, Unsubscribed__c, Unsubscribe_URL__c FROM Subscription_Map__c LIMIT 1];

        Test.startTest();
        RestRequest request = new RestRequest();
        request.httpMethod = 'GET';
        request.requestUri = subsMap.Unsubscribe_URL__c;

        System.debug('TEST_SubscriptionProcessor | Unscubscribe full URL: ' + request.requestUri);
        RestContext.request = request;
        RestContext.response = new RestResponse(); 

        // Invoke the doGet() Method of the SubscriptionProcessor
        SubscriptionProcessor.doGet();
        Test.stopTest();

        // After unsubscribe
        subsMap = [SELECT Id, GUID__c, Unsubscribed__c FROM Subscription_Map__c LIMIT 1];

        // The record should be in an Unsubscribed state (i.e., Unsubscribe__c == true)
        System.assertEquals (true, subsMap.Unsubscribed__c);
    }


    @isTest
    static void testNegativeDoGet () {

        final String BASE_URL_NAME = 'Subscription Processor';
        final String REST_URL = '/services/apexrest/SubscriptionProcessor/';

        String base_url = [SELECT Id, Base_URL__c FROM Base_URL__mdt WHERE MasterLabel = 'Subscription Processor' LIMIT 1].Base_URL__c;

        Test.startTest();
        RestRequest request = new RestRequest();
        request.httpMethod = 'GET';
        request.requestUri = base_url+REST_URL+'a6s5d5f4e8d5s4s6d8d65s4s254e54t';

        System.debug('TEST_SubscriptionProcessor | Unscubscribe full URL: ' + request.requestUri);
        RestContext.request = request;
        RestContext.response = new RestResponse(); 

        // Invoke the doGet() Method of the SubscriptionProcessor
        SubscriptionProcessor.doGet();
        Test.stopTest();

        // After unsubscribe
        Subscription_Map__c subsMap = [SELECT Id, GUID__c, Unsubscribed__c FROM Subscription_Map__c LIMIT 1];

        // The record should still be in a Subscribed state (i.e., Unsubscribe__c == false)
        System.assertEquals (false, subsMap.Unsubscribed__c);
    }
}