mdapipkg/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>FirstName_SPE__c</fullName>
        <description>Encrypted First Name For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>First Name (PE)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <inlineHelpText>Please select the gender of the member.
M- Male
F- Female</inlineHelpText>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>Prefer not to mention</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LastName_SPE__c</fullName>
        <description>Encrypted Last Name For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Last Name (PE)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_City_SPE__c</fullName>
        <description>Encrypted Mailing City (PE) For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Mailing City (PE)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Country_SPE__c</fullName>
        <description>Encrypted Mailing Country (PE) For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Mailing Country (PE)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_State_Province_SPE__c</fullName>
        <description>Encrypted Mailing State (PE) For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Mailing State/Province (PE)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Street_SPE__c</fullName>
        <description>Encrypted Mailing Street (PE) For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Mailing  Street (PE)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Zip_Postal_Code_SPE__c</fullName>
        <description>Encrypted Mailing Zip/Postal Code (PE) For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Mailing Zip/Postal Code (PE)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonBirthdate_SPE__c</fullName>
        <description>Encrypted Birthdate For Members</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Birthdate (PE)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PersonEmail_SPE__c</fullName>
        <description>Encrypted Email For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Email (PE)</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone_SPE__c</fullName>
        <description>Encrypted Phone For Members</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Phone (PE)</label>
        <type>Phone</type>
    </fields>
</CustomObject>

force-app/main/default/classes/TEST_SubscriptionGenerator.cls
@isTest
public without sharing class TEST_SubscriptionGenerator {
 
    @TestSetup
    static void makeData() {

        // Step 1: Retrieve record type for Account
        RecordType recType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Member' AND SobjectType = 'Account' LIMIT 1];

        // Step 2: Create a test Member account
        Account testAcct = new Account(
                FirstName_SPE__c = 'Eduardo',
                FirstName = 'Eduardo',
                LastName_SPE__c = 'Dela Rosa - Unsubscribe',
                LastName = 'Dela Rosa - Unsubscribe',
                Gender__c = 'M',
                Mailing_City_SPE__c = 'Bella Vista',
                Mailing_Country_SPE__c = 'Australia',
                Mailing_State_Province_SPE__c = 'New South Wales',
                Mailing_Street_SPE__c = '1 Elizabeth Macarthur Drive',
                Mailing_Zip_Postal_Code_SPE__c = '2761',
                PersonBirthdate_SPE__c = Date.newInstance(2000,01,01),
                PersonEmail = 'eduardo.delarosa@resmed.com.au',
                PersonEmail_SPE__c = 'eduardo.delarosa@resmed.com.au',
                Phone_SPE__c = '0288842767',
                RecordTypeId = recType.Id,
                Salutation = 'Mr'
        );

        insert testAcct;
    }

    @isTest
    static void testCreateSubscriptionURL () {

        String SUBSCRIPTION_TYPE = 'Register Your Product';
        String BASE_URL_KEY = 'Subscription Processor';

        // Step 1: Query for Account Id
        String accId = [SELECT Id FROM Account LIMIT 1].Id;
        System.assert(accId != NULL);

        // Step 2: Get a new GUID using default crypto key (NULL)
        GUIDGenerator gg = new GUIDGenerator(NULL);
        String guid = gg.generateGUID(accId);
        System.assert(guid != NULL);

        SubscriptionGenerator sg = new SubscriptionGenerator();
        Boolean success = sg.createSubscriptionURL(SUBSCRIPTION_TYPE, accId, guid, BASE_URL_KEY);

        System.assertEquals(true, success);
    }

    @isTest
    static void testNegativeInvalidURLKey () {

        String SUBSCRIPTION_TYPE = 'Register Your Product';
        String BASE_URL_KEY = 'Non-Subscription Processor';

        // Step 1: Query for Account Id
        String accId = [SELECT Id FROM Account LIMIT 1].Id;
        System.assert(accId != NULL);

        // Step 2: Get a new GUID using default crypto key (NULL)
        GUIDGenerator gg = new GUIDGenerator(NULL);
        String guid = gg.generateGUID(accId);
        System.assert(guid != NULL);

        SubscriptionGenerator sg = new SubscriptionGenerator();
        Boolean success = sg.createSubscriptionURL(SUBSCRIPTION_TYPE, accId, guid, BASE_URL_KEY);

        System.assertEquals(false, success);
    }

    @isTest
    static void testNegativeInvalidAccountId () {

        String SUBSCRIPTION_TYPE = 'Register Your Product';
        String URL_KEY = 'Subscription Processor';

        // Step 1: Query for Account Id
        String accId = 'THIS\'SHOULD\"IVALIDATE()343&#@!';

        // Step 2: Get a new GUID using default crypto key (NULL)
        GUIDGenerator gg = new GUIDGenerator(NULL);
        String guid = gg.generateGUID(accId);
        System.assert(guid != NULL);

        SubscriptionGenerator sg = new SubscriptionGenerator();
        Boolean success = sg.createSubscriptionURL(SUBSCRIPTION_TYPE, accId, guid, URL_KEY);

        System.assertEquals(false, success);
    }
}