mdapipkg/objects/Base_URL__mdt.object
<CustomObject>
    <description>This is the base URL of the target site exposed to the internet. The format of this URL MUST BE in the form of https://&lt;instance&gt;.force.com/services/apexrest/&lt;restResourceURLMapping&gt;.

Example: http://dev4ed-resmed-anz.cs6.force.com/SubscriptionProcessor/&lt;parameter&gt;</description>
    <label>Base URL</label>
    <pluralLabel>Base URLs</pluralLabel>
    <fields>
        <fullName>Base_URL__c</fullName>
        <label>Base URL</label>
        <type>Url</type>
    </fields>
</CustomObject>

mdapipkg/objects/Subscription_Map__c.object
<CustomObject>
    <description>A mapping table designed to store a subscription GUID, subscription type (e.g., SV Product Registration, MA Study, etc.), request flag, and account lookup. A record will be created each time an email (e.g., news letter, thank you, welcome, etc.) gets generated by Salesforce.com. The GUID is a unique ID assigned for each subscription type - and is the subject of &quot;unsubscribe&quot; request from the end user. When unsubscribe request is received, it will set the opt-out flag for that specific subscription type.</description>
    <label>Subscription Map</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{000000}</displayFormat>
        <label>Subscription Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account to which this subscription is mapped against.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscription Maps</relationshipLabel>
        <relationshipName>Subscription_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>A custom generated GUID assigned to each subscription record.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>GUID</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of subscription, e.g., SV Product Registration, MA Study, etc.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unsubscribe_URL__c</fullName>
        <description>The URL to unsubscribe service.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Unsubscribe URL</label>
        <type>Url</type>
    </fields>
</CustomObject>

force-app/main/default/classes/SubscriptionGenerator.cls
/**
 * @author Eduardo Dela Rosa
 * @dateCreated 02-Mar-2020
 * @Descripion. SubscriptionGenerator is a utility class that will help create a record entry into 
 *              the Subscription Map table - which is utilized by the Subscription Processor REST API
 *              when an end customer chose to unsubscribe/opt-out from such subscription.
 */
public without sharing class SubscriptionGenerator {

    private static final String CLASS_NAME = 'SubscriptionGenerator.cls | ';
    private String locURL = NULL;

    /**
     * Description. This public would be invoked by client Apex classes when there's a need to create
     *              a subscription mapping between an account and subscription. This will build a new record 
     *              out of the GUID and URL and will be inserted the Subscription Map.
     * @param String type - the type of subscription to unsubscribe
     * @param String accId - the account Id to search for
     * @param String guid - the unique guid to set as paramater to the URL
     * @param String URLKey - the URLKey (MasterLabel) to retrieve from the Base_URL__mdt
     */
    public Boolean createSubscriptionURL (String type, String accId, String guid, String URLkey) {


        // Step 1. Validate and retrieve URLkey; see if a record is existing in the custom metadata setting
        this.locURL = getURL(URLkey); // assign the retrieve URL to the instance var
        if (this.locURL == NULL) {
            System.debug(CLASS_NAME + 'Can\'t do much, unable to retrieve the URL based on the URLkey - ' + URLkey);
            return false;
        }

        // Step 2. Build the whole unsubscribe URL and create an entry into the Subscription_Map__c
        String unsubURL = this.locURL.trim() + guid.trim();
        Subscription_Map__c mapRec = NULL;

        try {
             mapRec = new Subscription_Map__c(
                Unsubscribe_URL__c = unsubURL, 
                Type__c = type, 
                GUID__c = guid.trim(), 
                Account__c = accId);
    
                insert mapRec;
        } catch (Exception e) {
            System.debug(CLASS_NAME + 'Error while inserting new Subscription Map record with guid ' + guid.trim() + ' | Message ' + e.getMessage());
        }

        if (mapRec == NULL) {
            return false;
        }

        System.debug(CLASS_NAME + 'Subscription Map record successfully created | Value of Subscription_Map__c.GUID__c: ' + mapRec.GUID__c);
        return true;

    }

    private String getURL(String URLkey) {

        System.debug(CLASS_NAME + 'Inside the SubscriptionGenerator.getURL | Value of URLKkey: ' + URLkey);
        Base_URL__mdt urlObj = NULL;

        try {
            urlObj = [SELECT Id, Base_URL__c FROM Base_URL__mdt WHERE MasterLabel = :URLkey LIMIT 1];
            System.debug(CLASS_NAME + 'getURL() | After an attempt to retrieve the value of Base URL for Subscription Generator | Value of Base_URL__mdt.Base_URL__c: ' + urlObj.Base_URL__c);
        } catch (Exception e) {
            System.debug(CLASS_NAME + 'getURL() | Unable to validate URLKey | Error | ' + e.getMessage());
        }


        if (urlObj == NULL) { // something must have gone wrong when retrieving URLkey
            System.debug(CLASS_NAME + 'getURL() | Base_URL__mdt is NULL.');
            return NULL;
        }

        return urlObj.Base_URL__c;
    }
}